version: '3.3'

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:1.17.8
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app
    ports:
      - "${EXTERNAL_HTTP_PORT}:80"

  blue:
    container_name: ${COMPOSE_PROJECT_NAME}-blue
    image: $IMAGE_NAME:blue
    restart: always
    networks:
      - app

  green:
    container_name: green
    image: $IMAGE_NAME:green
    networks:
      - app

networks:
  app:
